### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by s-celles** [Mokolea/InputDebounce#2]
Hello @Mokolea ,

many Arduino libraries (such as those developed by Adafruit https://github.com/adafruit ) are using more permissive license such as MIT, BSD, LGPL (Library General public license) or Apache license.
Dual licensing will be a nice idea to allow developers to use this library without having to use same licence than this library.

Kind regards

**Comment by Mokolea** [comment]
Hi, you're right. I change the license to "Apache License 2.0"
Thanks

**Comment by s-celles** [comment]
Thanks a lot @Mokolea
