### ISSUE TITLE
Multiple buttons

### ISSUE THREAD

**Issue by HynekBaran** [Mokolea/InputDebounce#3]
Hi,
what about a situation when multiple buttons are used? 
When callback functions are used, then possible simplification is such that  the button's PIN number will be passed as an argument to the callback functions (so they may be common for all the buttons).
Thanks
Hynek

**Comment by Mokolea** [comment]
Hi, good idea, thanks
I think I will implement this, I let you know when it's done
Mario

**Comment by Mokolea** [comment]
Done, see v1.3.0
